name: Build
on: [ push ]
concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Java
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 23

      - name: Cache Dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository/*
          key: ${{ runner.OS }}-maven-${{ hashFiles('**/pom.xml') }}

      # Maven command-line options:
      # --batch-mode: recommended in CI to inform maven to not run in interactive mode (less logs)
      # -V: strongly recommended in CI, will display the JDK and Maven versions in use.
      # -Dsurefire.useFile=false: useful in CI. Displays test errors in the logs directly (instead of
      #                           having to crawl the workspace files to see the cause).
      # -e: Display stack-traces on failure
      - name: Build
        run: ./mvnw verify --batch-mode -V "-Dsurefire.useFile=false" -e